name: Create release on tag

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  test_chrome:
    name: Test chrome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y jq
      - name: Check manifest version
        run: |
          version="$(jq -r '.version' chrome/manifest.json)"
          echo "$version" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$'
  test_mozilla:
    name: Test mozilla
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y jq
      - name: Check manifest version
        run: |
          version="$(jq -r '.version' mozilla/manifest.json)"
          echo "$version" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$'
  build_mozilla:
    name: Build mozilla
    needs:
      - test_mozilla
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y zip build-essential

      - name: Build
        run: |
          make mozilla

      - name: Save xpi file
        uses: actions/upload-artifact@v4
        with:
          name: mozilla_release
          path: ./rosettastonks.xpi

  build_chrome:
    name: Build chrome
    needs:
      - test_chrome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y build-essential

      - name: Build
        run: |
          make chrome
          tar cvzf rosettastonks-chrome.tar.gz dist/ static/ manifest.json

      - name: Save xpi file
        uses: actions/upload-artifact@v4
        with:
          name: chrome_release
          path: ./rosettastonks-chrome.tar.gz

  release:
    needs:
      - build_chrome
      - build_mozilla
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download chrome release
        uses: actions/download-artifact@v4
        with:
          name: chrome_release
      - name: Download mozilla release
        uses: actions/download-artifact@v4
        with:
          name: mozilla_release
      - name: Create github release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "rosettastonks.xpi,rosettastonks-chrome.tar.gz"
